# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Rahvana
tagline:             'thougts and writings'
description:         ''
url:                 https://martabacc.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              '-'
  url:               https://google.com
  email:             ronayumik@gmail.com

# Custom vars
version:             1.0.0

defaults:
  - scope:
      path: "public/post"
    values:
      image: true

plugins:
  - jekyll-paginate
